name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/60 * * * *' # Every 60 minutes
  workflow_dispatch: # lets you manually trigger it

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          echo "Pinging Streamlit app..."
          curl -s -o /dev/null -w "%{http_code}" https://your-streamlit-app.streamlit.app/
